[package]
name = "rust-rendering"
version = "0.1.0"
edition = "2021"

[dependencies.rust-embree]
path = "../rust-embree"

[dependencies]
nalgebra = "0.33.0"


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "raygen_benchmark"
harness = false
