[package]
name = "rust-rendering"
version = "0.1.0"
edition = "2021"

[dependencies.rust-embree]
path = "/home/mujin/workdesk/rust-embree"

[dependencies]
eframe = "0.28.1"
image = "0.25.2"
nalgebra = "0.33.0"
raylib = "5.0.1"

